Feat/input email
kalNascimento/gym-ranked pull request #9
Opened 2023-10-05 22:28 UTC by quaresmina

Este PR:
- Adiciona a biblioteca React Hook Forms;
- Troca a versão da biblitoteca Styled Components, para melhor aproveitamento no projeto;
- Cria o componente TextInput;
- Cria o component Text, com estilizações de texto próprias do projeto;
- Cria o formulário de cadastro com os inputs de EMAIL, SENHA e CONFIRMAR SENHA com suas validações;

[CARD PRINCIPAL](https://trello.com/c/XTS57KXr)

2023-10-06 14:07 UTC, kalNascimento requested changes

2023-10-06 14:07 UTC, kalNascimento commented on src/screens/Register/index.tsx
Acho q vc pode seguir essa ideia de componentizar mais uma vez os inputs


![image](https://github.com/kalNascimento/gym-ranked/assets/60221532/58bd7b18-6d5b-4705-af16-97d3a9bd5fdf)
![image](https://github.com/kalNascimento/gym-ranked/assets/60221532/626ed86b-669f-4f4e-a60b-3996304a3e59)


como vantagem vai diminuir a quantidade de código dentro do formulario

2023-10-06 14:07 UTC, kalNascimento commented on src/screens/Register/index.tsx
> +            rules={{
tambem pode tentar extrair as rules, para reaproveitar elas em outras telas, ja q uma rule escrita para email sempre vai ser igual

2023-10-06 14:07 UTC, kalNascimento commented on src/screens/Register/index.tsx
> +          <NormalText>
pode refatorar essa parte para usar o component Text que vc criou

2023-10-06 14:07 UTC, kalNascimento commented on src/screens/Register/index.tsx
> +          <Controller
considerando que é um input de senha talvez fosse interessante ter a propriedade  [secureTextEntry](https://reactnative.dev/docs/textinput#securetextentry)

2023-10-07 20:50 UTC, systemagic-91 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Formulário de Cadastro](https://trello.com/c/XTS57KXr/28-formul%C3%A1rio-de-cadastro)

2023-11-20 13:34 UTC, kalNascimento approved these changes

2023-11-21 20:08 UTC, systemagic-91 approved these changes
ATÉ QUE ENFIM!

2023-11-21 20:09 UTC, merged